name: Feyd's Spell Marker
on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    if: contains(github.event.head_commit.message, 'version bump')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      id: nvm
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

    - name: Install and link dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Get Version
      uses: culshaw/read-package-node-version-actions@v1
      id: version
      with:
        path: './modules/feyds-spell-marker'

    - name: Prepare Release
      run: |
        cd ./modules/feyds-spell-marker
        zip -r ./feyds-spell-marker.zip ./dist module.json

    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: './modules/feyds-spell-marker/CHANGELOG.md'
        tag_name: feyds-spell-marker@${{ steps.version.outputs.version }}
        release_name: Feyd's Spell Marker ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./modules/feyds-spell-marker/feyds-spell-marker.zip
        asset_name: feyds-spell-marker.zip
        asset_content_type: application/zip

